### ISSUE TITLE
Import images from CSV

### ISSUE THREAD

**Issue by barbudour** [lazurey/strapi-plugin-content-export-import#1]
Hi, this is a great import plugin. I am importing an article database into my application and have encountered the difficulty of importing images. I have a field in the table with paths to the images and a folder with these images. How do I import them correctly using your plugin? Thanks

**Comment by lazurey** [comment]
Hi @barbudour , unfortunately it doesn't support the media assets import. I haven't got time to work on that.

You can refer to [this guide](https://strapi.io/blog/how-to-create-an-import-content-plugin-part-1-4), it mentioned how to import media assets. But you need to create your own plugin, or fork this one and start from here.

**Comment by barbudour** [comment]
@lazurey thanks, I tried to do this guide
