### ISSUE TITLE
How to use the plugin?

### ISSUE THREAD

**Issue by avitorio** [lazurey/strapi-plugin-content-export-import#10]
Hi,
I'm sorry if this may be too obvious to some, but I'm new to Strapi and not too familiar how plugins should work.
I have installed Strapi following the [Quick Start guide](https://strapi.io/documentation/v3.x/getting-started/quick-start.html).

I then followed the instructions in this repository.
I've installed the content-export-import plugin and I can see in the list of plugins, but I don't see any options for uploading my JSON file.

![image](https://user-images.githubusercontent.com/1417109/88466756-f7d98000-cecf-11ea-9346-225ac16ae488.png)

Any help is highly appreciated. Thanks.

**Comment by avitorio** [comment]
I just managed to access it by going to: http://localhost:1337/admin/plugins/content-export-import/
Hope this helps someone else.

**Comment by arnaudjnn** [comment]
Why the plugin is not showing on the left menu?

**Comment by lazurey** [comment]
Not sure, maybe try to login with admin account?

**Comment by avitorio** [comment]
I was signed as admin.

**Comment by avitorio** [comment]
I'll close the issue since I haven't had time to revisit it.

**Comment by fadhilx** [comment]
@lazurey Why the plugin is not showing on the left menu, i was signed in as admin. 

Reproduce:
1. create strapi project
2. and then add the plugin using `yarn add strapi-plugin-content-export-import` or npm
3. serve `yarn develop`

**Comment by SalahAdDin** [comment]
@fadhilx it won't work like that, i don't understand why, you should add this repository as a module dependency.
